version: '3.7'

services:
  fmu:
    container_name: test_generator
    build: .  # create bash script for 'command' below
              # script will find .idf, .idd, an .epw file and produce .fmu
    command:  bash -c "cd /home/fmu/code/energy/test &&
              python  /home/fmu/code/energy/Scripts/EnergyPlusToFMU.py
              -d
              -i  /home/fmu/code/Energy+.idd
              -w  /home/fmu/code/USA.epw
              /home/fmu/code/_fmu-export-variable.idf
              && ./idf-to-fmu-export-prep-linux
              /home/fmu/code/Energy+.idd
              /home/fmu/code/_fmu-export-variable.idf"
    volumes:
      - ./volume:/home/fmu/code/energy/test