version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
        - "RABBITMQ_DEFAULT_PASS=pass"
        - "RABBITMQ_DEFAULT_USER=user"
        - "RABBITMQ_DEFAULT_VHOST=vhost"
    container_name: broker
    networks:
      - simapi
    restart: always

  celery_result_db:
    container_name: backend
    image: postgres
    environment:
      POSTGRES_DB: "backend_db"
      POSTGRES_PASSWORD: "backend"
    networks:
      - simapi
    ports:
      - 5434:5432
    volumes:
      - postgres_celery_data:/var/lib/postgresql/data/
    restart: always

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "db_pass"
    networks:
      - simapi
    ports:
    - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  web:
    container_name: web
    build: ./simapi_web
    command:  bash -c "python manage.py runserver 0.0.0.0:8000
                    & python manage.py migrate
                    & celery -A simapi_web worker -l info --concurrency=1 --queues=web"
    volumes:
      - ./simapi_web:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - simapi
    restart: always

  generator:
    container_name: generator
    build: ./simapi_simulation/fmu_generator
    command: bash -c "/run.sh"
    volumes:
      - ./simapi_simulation/fmu_simulator/fmu_location:/home/fmu/code/fmu_location
    ports:
      - 8001:8000
    depends_on:
      - web
    networks:
      - simapi
    restart: always

  simulator:
    build: ./simapi_simulation/fmu_simulator
    command: bash -c "/run.sh"
    volumes:
    # - ./simapi_simulation/fmu_simulator:/home/deb/code
    - ./simapi_simulation/fmu_simulator/volume:/home/deb/code/volume
    - ./simapi_simulation/fmu_simulator/fmu_location:/home/deb/code/fmu_location
    ports:
      - 8002-8102:8000
    depends_on:
      - web
      - generator
    networks:
      - simapi
    restart: always

networks:
  simapi:
    driver: bridge
volumes:
  postgres_data:
  postgres_celery_data:
